Update upstream.yml

diff --git a/.github/workflows/upstream.yml b/.github/workflows/upstream.yml
--- a/.github/workflows/upstream.yml
+++ b/.github/workflows/upstream.yml
@@ -1,30 +1,33 @@
-name: Sync packages
+#
+# This is free software, lisence use MIT.
+# 
+# 
+# <https://github.com/wixxm/wikjxwrt-luci>
+#
 
+name: Merge-upstream
 on:
   push:
     paths:
-      - '.github/workflows/wall.yml'
-      - '.github/diy/main.sh'
+      - '.github/workflows/upstream.yml'
+      - '.gitignore'
+      - '.github/diy/**'
   schedule:
     - cron: 0 */12 * * *
-  repository_dispatch:
   workflow_dispatch:
     inputs:
-      packages:
-        description: 'packages'
+      ssh:
+        description: 'ssh'
         required: false
-        default: 'false'	
+        default: 'true'
+  watch:
+    types: started
+  repository_dispatch:
 
 jobs:
-  build:
-    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
-    runs-on: ubuntu-latest
-
-    name: Update ${{matrix.target}}
-    strategy:
-      fail-fast: false
-      matrix:
-        target: [main]
+  merge:
+    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id || github.event.sender.id == '119362912'
+    runs-on: Ubuntu-22.04
 
     steps:
     - name: Checkout
@@ -32,52 +35,87 @@ jobs:
       with:
         fetch-depth: 0
 
-    - name: Initialization environment
+    - uses: de-vri-es/setup-git-credentials@v2
+      with:
+        credentials: https://kiddin9:${{ secrets.TOKEN_KIDDIN9 }}@github.com/
+    
+    - name: Set git identity
       run : |
-        git config --global user.email "419691642@qq.com"
-        git config --global user.name "wixxm"
+        git config --global user.email "github-actions[bot]@users.noreply.github.com"
+        git config --global user.name "github-actions[bot]"
         sudo timedatectl set-timezone "Asia/Shanghai"
-        
-    - name: Clone packages
-      run: |
-        cd $GITHUB_WORKSPACE
-        chmod +x .github/diy/${{matrix.target}}.sh
-        git clone -b ${{matrix.target}} https://github.com/kenzok8/small-package.git ${{matrix.target}}
-        cd ${{matrix.target}}
-        git rm -r --cache * >/dev/null 2>&1 &
-        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
-        $GITHUB_WORKSPACE/.github/diy/${{matrix.target}}.sh
-        patch -p1 < $GITHUB_WORKSPACE/.github/diy/patches/homeproxy.patch
-        bash /$GITHUB_WORKSPACE/.github/diy/convert_translation.sh
-        bash /$GITHUB_WORKSPACE/.github/diy/create_acl_for_luci.sh -a
-        bash /$GITHUB_WORKSPACE/.github/diy/Modify.sh
 
-    - name: Upload
-      env: 
-        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+    - name: Syn upstream
       run: |
-        if [ -e $GITHUB_WORKSPACE/LICENSE ]; then
-          cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
-        fi
-        if [ -e $GITHUB_WORKSPACE/README.md ]; then
-          cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
-        fi
-        cd $GITHUB_WORKSPACE/${{matrix.target}}
-        if git status --porcelain | grep .; then
-          git add .
-          git commit -am "update $(date '+%Y-%m-%d %H:%M:%S')"
-          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/kenzok8/small-package.git" HEAD:${{matrix.target}}
+        shopt -s extglob
+        set +e
+        git rm -r --cache * >/dev/null 2>&1 &
+        rm -rf `find ./* -maxdepth 0 -type d ! -name ".github/diy"` >/dev/null 2>&1
+        function git_clone() {
+          git clone --depth 1 $1 $2
+          if [ "$?" != 0 ]; then
+            echo "error on $1"
+            pid="$( ps -q $$ )"
+            kill $pid
+          fi
+        }
+        function git_sparse_clone() {
+        trap 'rm -rf "$tmpdir"' EXIT
+        branch="$1" curl="$2" && shift 2
+        rootdir="$PWD"
+        tmpdir="$(mktemp -d)" || exit 1
+        if [ ${#branch} -lt 10 ]; then
+        git clone -b "$branch" --depth 1 --filter=blob:none --sparse "$curl" "$tmpdir"
+        cd "$tmpdir"
         else
-          echo "nothing to commit"
-          exit 0
-        fi || exit 0
+        git clone --filter=blob:none --sparse "$curl" "$tmpdir"
+        cd "$tmpdir"
+        git checkout $branch
+        fi
+        if [ "$?" != 0 ]; then
+            echo "error on $curl"
+            exit 1
+        fi
+        git sparse-checkout init --cone
+        git sparse-checkout set "$@"
+        mv -n $@ $rootdir/ || true
+        cd $rootdir
+        }
+        function mvdir() {
+        mv -n `find $1/* -maxdepth 0 -type d` ./
+        rm -rf $1
+        }
+       (
+        #git_clone https://github.com/jerrykuku/luci-app-vssr
+        #git_clone https://github.com/jerrykuku/luci-app-ttnode
+        git_clone https://github.com/sirpdboy/luci-app-advancedplus
+        git_clone https://github.com/sirpdboy/luci-app-autotimeset
+        git_clone https://github.com/sirpdboy/luci-app-lucky oplucky && mv -f oplucky/*/ ./ && rm -rf oplucky
+        git_clone https://github.com/sirpdboy/luci-app-partexp
+        git_clone https://github.com/sirpdboy/luci-app-ddns-go ddns-go1 && mvdir ddns-go1
+        git_clone https://github.com/sirpdboy/netspeedtest && mv -n netspeedtest/luci-app-netspeedtest ./ ; rm -rf netspeedtest
+        git_clone https://github.com/sirpdboy/luci-app-parentcontrol
+        git_clone https://github.com/sirpdboy/luci-app-poweroffdevice
+        # git_clone https://github.com/muink/luci-app-homeproxy
+        ) &
+- name: Apply
+      run: |
+        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
+        git add .
+        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
+        for pkg in $(git diff-tree --no-commit-id --name-only HEAD); do
+          if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
+            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count main $pkg)/" $pkg/Makefile || true
+          fi
+        done
+        git reset --soft HEAD^
+        git add .
+        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
+        git push -f
 
     - name: Delete workflow runs
       uses: Mattraks/delete-workflow-runs@main
+      continue-on-error: true
       with:
-        token: ${{ github.token }}
-        repository: ${{ github.repository }}
         retain_days: 1
-        keep_minimum_runs: 1
-
- 
+        keep_minimum_runs: 3
